#!/usr/bin/env bash
#  Based on answer by Juergen Weiger at Stack Overflow entry http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container

test -f tag.sh && source ./tag.sh

if [ "$1" == "--use-display" ]; then
    DISPLAY_ARGS="--net=host -e DISPLAY=$DISPLAY"
else
    XAUTH=/tmp/.docker.xauth
    xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
    DISPLAY_ARGS="-v /tmp/.X11-unix:/tmp/.X11-unix -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH -e DISPLAY"
fi

docker run --rm $DISPLAY_ARGS -e UNAME=$USER -e UID=$(id -u $USER) -e GID=$(id -g $USER) -v ~/:$(echo ~) ${TAG:-jordi/golang-devel:33.3-beta}
